import type { Metadata } from "next";
import { The_Nautigal } from 'next/font/google'
import Header from "./components/Header";
import Footer from "./components/Footer";

import "./globals.css";

const nautigal = The_Nautigal({
  subsets: ['latin'],
  weight: ['400', '700'], // available weights
  variable: '--font-nautigal',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <html lang="en" >

      <body
        className={`${nautigal.variable} antialiased`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
